const cors = require('cors')
const express = require('express')
const morgan = require('morgan')
const dotenv = require('dotenv')
dotenv.config({ path: 'server.env'})
const accountRoute = require('./routes/account-route')
const auctionProductRoute = require('./routes/auction-product-route')
const bannerRoute = require('./routes/banner-route')
const financeRoute = require('./routes/finance-route')
const gachaProductRoute = require('./routes/gacha-product-route')
const gameNameRoute = require('./routes/game-name-route')
const historyPaymentRoute = require('./routes/history-payment-route')
const historyProductRoute = require('./routes/history-product-route')
const normalProductRoute = require('./routes/normal-product-route')
const paymentMethodRoute = require('./routes/payment-method-route')
const storeProductRoute = require('./routes/store-product-route')
const app = express()

app.use(express.json())
app.use(cors())
app.use(morgan('dev'))

// app.use('/api', homeRoute)
// app.use('/api', signUpRoute)
// app.use('/api', signInRoute)
// app.use('/api', mediaRoute)
// app.use('/api', preferenceRoute)
// app.use('/api', editAccountRoute)
// app.use('/api', friendsRoute)

const port = process.env.PORT || 8080
app.listen(port, () => {
    console.log(`server at http://localhost:${port}/`)
})